"""esquema inicial

Revision ID: 1c9c07620028
Revises: 
Create Date: 2026-09-16 19:47:54.400237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9c07620028'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acopio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_recoleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=False),
    sa.Column('generado_en', sa.DateTime(), nullable=False),
    sa.Column('version_metodo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('municipio', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('capacidad_racimos', sa.Integer(), nullable=False),
    sa.Column('disponible_desde', sa.DateTime(), nullable=False),
    sa.Column('disponible_hasta', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coeficiente_consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('productor_id', sa.Integer(), nullable=False),
    sa.Column('valor_por_racimo', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['productor_id'], ['productor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insumo_id', 'productor_id')
    )
    op.create_table('parcela',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('productor_id', sa.Integer(), nullable=False),
    sa.Column('area_ha', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('acopio_id', sa.Integer(), nullable=False),
    sa.Column('tiempo_acarreo_min', sa.Integer(), nullable=False),
    sa.Column('medio_acarreo', sa.String(length=20), nullable=False),
    sa.Column('capacidad_medio_racimos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acopio_id'], ['acopio.id'], ),
    sa.ForeignKeyConstraint(['productor_id'], ['productor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requerimiento_insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('cantidad_requerida', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deficit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_recoleccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventana_despacho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acopio_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acopio_id'], ['acopio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aforamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('num_plantas', sa.Integer(), nullable=False),
    sa.Column('calidad_confianza', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.String(length=50), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=False),
    sa.Column('cantidad_disponible', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('insumo_id', 'parcela_id', 'periodo')
    )
    op.create_table('item_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.String(length=50), nullable=False),
    sa.Column('fecha_corte', sa.DateTime(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('carga_estimada_racimos', sa.Integer(), nullable=False),
    sa.Column('cumple_ventana', sa.Boolean(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_recoleccion.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyeccion_cosecha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.String(length=50), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=False),
    sa.Column('volumen_racimos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcela_id', 'periodo', 'metodo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proyeccion_cosecha')
    op.drop_table('item_plan')
    op.drop_table('inventario')
    op.drop_table('aforamiento')
    op.drop_table('ventana_despacho')
    op.drop_table('requerimiento_insumo')
    op.drop_table('parcela')
    op.drop_table('coeficiente_consumo')
    op.drop_table('vehiculo')
    op.drop_table('productor')
    op.drop_table('plan_recoleccion')
    op.drop_table('insumo')
    op.drop_table('acopio')
    # ### end Alembic commands ###
